### ISSUE TITLE
背景图似乎有些异常条纹？

### ISSUE THREAD

**Issue by whuwangyong** [Morganwan90/Darkblue-siyuan-theme#1]
如图，左边栏、右边栏、顶栏等等。还是说故意这么设计的？
思源版本为最新的1.8.4

![image](https://user-images.githubusercontent.com/5968678/155937972-038652c5-8b9a-4bfd-94e9-66a3e95cd23b.png)

**Comment by Morganwan90** [comment]
那个是背景图...
你可以把你喜欢的背景放替换到主题 “Dark Blue\img\bg.jpg"

**Comment by whuwangyong** [comment]
hahah，好的好的
