### ISSUE TITLE
透明的悬浮边栏影响可读性

### ISSUE THREAD

**Issue by JARVISia** [Morganwan90/Darkblue-siyuan-theme#3]
![image](https://user-images.githubusercontent.com/16850140/224895002-d7c6f8ff-5f41-4f6c-b4a8-875f7ed6009c.png)

这个边栏的透明感觉影响边栏内容的阅读，是否考虑改成不透明？或者考虑改透明度低一些？

**Comment by Morganwan90** [comment]
是移动端么，我在ios和安卓上看都OK得...我记得以前改过这个问题，手机上的主题是最新版的么

**Comment by JARVISia** [comment]
> 是移动端么，我在ios和安卓上看都OK得...我记得以前改过这个问题，手机上的主题是最新版的么

这是电脑的客户端

**Comment by Morganwan90** [comment]
做了调整，谢谢反馈~
