### ISSUE TITLE
上架的时候，DisplayName 填错了

### ISSUE THREAD

**Issue by frostime** [Morganwan90/Darkblue-siyuan-theme#4]
![image](https://github.com/Morganwan90/Darkblue-siyuan-theme/assets/27268127/e7baeec2-4eb0-4284-a638-b25a90f09924)

![image](https://github.com/Morganwan90/Darkblue-siyuan-theme/assets/27268127/9aefbcb0-0b4e-4c34-a11b-e1ad6793a951)

**Comment by Morganwan90** [comment]
啊哈.........谢谢，我改一下....
