### ISSUE TITLE
代码块似乎对不齐了，样式似乎也被改变了

### ISSUE THREAD

**Issue by qing3feng** [Morganwan90/Darkblue-siyuan-theme#6]
<img width="867" alt="Snipaste_2024-08-31_15-15-19" src="https://github.com/user-attachments/assets/ba90920b-5d0f-4d78-a19e-fca91b29afd6">

这是更新后的问题，不知道是siyuan的问题还是主体的问题

**Comment by Morganwan90** [comment]
修正了一下，谢谢两位用我的主题~
